// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reset.sql

package database

import (
	"context"
)

const resetPosts = `-- name: ResetPosts :exec
DELETE FROM posts
`

func (q *Queries) ResetPosts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetPosts)
	return err
}

const resetReports = `-- name: ResetReports :exec
DELETE FROM reports
`

func (q *Queries) ResetReports(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetReports)
	return err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}
